const DEFAULT_REFRESH_INTERVAL_MINUTES = 5;
const MIN_REFRESH_INTERVAL_MINUTES = 1;
const MAX_REFRESH_INTERVAL_MINUTES = 240;

const PROVIDERS_DIRECTORY_NAME = "providers";

module.exports = {
    DEFAULT_REFRESH_INTERVAL_MINUTES,
    MIN_REFRESH_INTERVAL_MINUTES,
    MAX_REFRESH_INTERVAL_MINUTES,
    PROVIDERS_DIRECTORY_NAME,
};
