const DEFAULT_REFRESH_INTERVAL_MINUTES = 5;
const MIN_REFRESH_INTERVAL_MINUTES = 1;
const MAX_REFRESH_INTERVAL_MINUTES = 240;
const DEFAULT_INITIAL_REFRESH_DELAY_SECONDS = 5;
const MIN_INITIAL_REFRESH_DELAY_SECONDS = 1;
const MAX_INITIAL_REFRESH_DELAY_SECONDS = 300;

const PROVIDERS_DIRECTORY_NAME = "providers";

module.exports = {
    DEFAULT_REFRESH_INTERVAL_MINUTES,
    MIN_REFRESH_INTERVAL_MINUTES,
    MAX_REFRESH_INTERVAL_MINUTES,
    DEFAULT_INITIAL_REFRESH_DELAY_SECONDS,
    MIN_INITIAL_REFRESH_DELAY_SECONDS,
    MAX_INITIAL_REFRESH_DELAY_SECONDS,
    PROVIDERS_DIRECTORY_NAME,
};
